name: Build and deploy .NET app to Azure Web App
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install NuGet
      run: |
        sudo apt-get install -y nuget
    - name: Restore packages
      run: |
        nuget restore "CRUD application 2.sln"
    - name: Build
      run: msbuild /p:Configuration=Release "CRUD application 2.sln"
    - name: Publish
      run: dotnet publish "CRUD application 2.sln" --configuration Release --output ./publish
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AmalTestApp'
        slot-name: 'production' # Change this if you have a different slot name
        # publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./output